**Creating Token Embedding**

In [12]:
import torch
input_ids = torch.tensor([2,3,5,1])

For simplicity we will take 6 as vocab_size and 3 as embedding size

In [13]:
vocab_size = 6
output_dim = 3

torch.manual_seed(123)
embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

In [15]:
# initialized weight is random
print(embedding_layer.weight)

Parameter containing:
tensor([[ 0.3374, -0.1778, -0.1690],
        [ 0.9178,  1.5810,  1.3010],
        [ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-1.1589,  0.3255, -0.6315],
        [-2.8400, -0.7849, -1.4096]], requires_grad=True)


These above values are optimized during LLM training and each row represent token id.

In [18]:
print(embedding_layer(torch.tensor([3]))) # for id no. 3

tensor([[-0.4015,  0.9666, -1.1481]], grad_fn=<EmbeddingBackward0>)


In [20]:
print(embedding_layer(input_ids)) # for input_ids lookup i.e. 2,3,5,1.

tensor([[ 1.2753, -0.2010, -0.1606],
        [-0.4015,  0.9666, -1.1481],
        [-2.8400, -0.7849, -1.4096],
        [ 0.9178,  1.5810,  1.3010]], grad_fn=<EmbeddingBackward0>)


**The lookup operation for the required ids is called embedding_layer.**